#!/bin/bash

# enable nbserverproxy
jupyter serverextension enable --sys-prefix nbserverproxy

# Service A
# install the flask server extension so that
# flask launches at startup
mv flaskserverextension-A.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable bokeh extension
jupyter serverextension enable --sys-prefix flaskserverextension-A

# Service B
# install the flask server extension so that
# flask launches at startup
mv flaskserverextension-B.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable bokeh extension
jupyter serverextension enable --sys-prefix flaskserverextension-B

# Service C
# install the flask server extension so that
# flask launches at startup
mv flaskserverextension-C.py ${NB_PYTHON_PREFIX}/lib/python*/site-packages/
# enable bokeh extension
jupyter serverextension enable --sys-prefix flaskserverextension-C